import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#006d43",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-secondary": "#1c1b1b",
        "surface-variant": "#353535",
        "surface": "#000000",
        "tertiary-container": "#00a668",
        "on-surface": "#ffffff",
        "outline-variant": "#474747",
        "on-secondary-fixed-variant": "#3c3b3b",
        "tertiary": "#52ffac",
        "primary-container": "#d4d4d4",
        "tertiary-fixed-dim": "#005231",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "primary": "#ffffff",
        "on-tertiary": "#002111",
        "primary-fixed-dim": "#454747",
        "primary-fixed": "#5d5f5f",
        "on-tertiary-fixed-variant": "#52ffac",
        "on-tertiary-container": "#000000",
        "on-secondary-container": "#e5e2e1",
        "surface-container-high": "#1a1a1a",
        "secondary-container": "#474646",
        "on-primary-fixed": "#ffffff",
        "secondary-fixed": "#c8c6c5",
        "inverse-on-surface": "#303030",
        "surface-container-highest": "#222222",
        "on-secondary-fixed": "#1c1b1b",
        "surface-bright": "#393939",
        "on-primary": "#000000",
        "secondary": "#c8c6c5",
        "background": "#000000",
        "secondary-fixed-dim": "#adabaa",
        "error-container": "#93000a",
        "inverse-surface": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "outline": "#919191",
        "on-surface-variant": "#c6c6c6",
        "on-primary-container": "#000000",
        "inverse-primary": "#5d5f5f",
        "surface-dim": "#000000",
        "on-background": "#ffffff",
        "surface-tint": "#c6c6c7",
        "surface-container-lowest": "#000000",
        "surface-container": "#111111",
        "surface-container-low": "#0a0a0a",
        "on-tertiary-fixed": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};
export default config;
